package com.spm.viettel.msm.dto;

import lombok.Data;

@Data
public class TargetChannelDto {
    private String brCode;
    private String bcCode;
    private String staffCode;
    private String channelTypeName;
    private Long channelTypeId;
    private Integer newTarget;
    private Integer newPlan;
    private Integer newResult;
    private Integer accummTarget;
    private Integer accummResult;
    private Integer t1NewTarget;
    private Integer t1NewPlan;
    private Integer t1NewResult;
    private Integer t2NewTarget;
    private Integer t2NewPlan;
    private Integer t2NewResult;
    private Integer t3NewTarget;
    private Integer t3NewPlan;
    private Integer t3NewResult;
    private Integer t4NewTarget;
    private Integer t4NewPlan;
    private Integer t4NewResult;
    private Integer t5NewTarget;
    private Integer t5NewPlan;
    private Integer t5NewResult;
    private Integer t6NewTarget;
    private Integer t6NewPlan;
    private Integer t6NewResult;
    private Integer t7NewTarget;
    private Integer t7NewPlan;
    private Integer t7NewResult;
    private Integer t8NewTarget;
    private Integer t8NewPlan;
    private Integer t8NewResult;
    private Integer t9NewTarget;
    private Integer t9NewPlan;
    private Integer t9NewResult;
    private Integer t10NewTarget;
    private Integer t10NewPlan;
    private Integer t10NewResult;
    private Integer t11NewTarget;
    private Integer t11NewPlan;
    private Integer t11NewResult;
    private Integer t12NewTarget;
    private Integer t12NewPlan;
    private Integer t12NewResult;
    private Integer t1AccummTarget;
    private Integer t1AccummResult;
    private Integer t2AccummTarget;
    private Integer t2AccummResult;
    private Integer t3AccummTarget;
    private Integer t3AccummResult;
    private Integer t4AccummTarget;
    private Integer t4AccummResult;
    private Integer t5AccummTarget;
    private Integer t5AccummResult;
    private Integer t6AccummTarget;
    private Integer t6AccummResult;
    private Integer t7AccummTarget;
    private Integer t7AccummResult;
    private Integer t8AccummTarget;
    private Integer t8AccummResult;
    private Integer t9AccummTarget;
    private Integer t9AccummResult;
    private Integer t10AccummTarget;
    private Integer t10AccummResult;
    private Integer t11AccummTarget;
    private Integer t11AccummResult;
    private Integer t12AccummTarget;
    private Integer t12AccummResult;
}
